library/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required, Length


class AddQuestionForm(Form):
    questionname = StringField('Question Title', validators=[Required(), Length(1, 128)])
    questiontext = TextAreaField('Question Body', validators=[Required(), Length(1, 999)])
    submit = SubmitField('Add Question')


class AddAnswerForm(Form):
    text = StringField('Your Answer', validators=[Required(), Length(1, 999)])
    submit = SubmitField('Answer')

library/__init__.py
from config import config

from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint

    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

library/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

library/main/views.py
from flask import render_template, redirect, url_for, flash, request
from flask.ext.login import login_required, current_user
from . import main
from ..dao import Question, Answer
from ..model import insert_to_db
from .forms import AddQuestionForm, AddAnswerForm


@main.route('/')
def index_html():
    # current_app.logger.error('An error occurred')
    return redirect(url_for('main.show_questions'))


@main.route('/show_questions', methods=['GET', 'POST'])
def show_questions():
    questions = Question.query.all()
    form = AddQuestionForm()
    if form.validate_on_submit():
        question = Question(questionname=form.questionname.data, text=form.questiontext.data,
                            author=current_user._get_current_object())
        insert_to_db(question)
        flash('The question has been added.')
        return redirect(url_for('main.show_questions'))
    return render_template('questions.html', questions=questions, current_user=current_user, form=form)


@main.route('/question/<int:id>', methods=['GET', 'POST'])
def show_question(id):
    question = Question.query.filter_by(id=id).first()
    answers = Answer.query.filter_by(questionid=id).order_by('timestamp').all()
    form = AddAnswerForm()
    if form.validate_on_submit():
        answer = Answer(text=form.text.data, question=question, author=current_user._get_current_object())
        insert_to_db(answer)
        flash('The answer has been added.')
        return redirect(url_for('main.show_question', id=id))
    return render_template('question.html', answers=answers, current_user=current_user, form=form,
                           question=question)


@main.route('/search_for_question/', methods=['POST'])
@login_required
def search_for_question():
    search_text = request.form['search_text']
    questions = Question.query.filter(Question.text.like("%" + search_text + "%")).all()
    form = AddQuestionForm()
    return render_template('questions.html', questions=questions, current_user=current_user, form=form)


# TODO Make POST here!!!
@main.route('/like/<int:id>', methods=['GET'])
@login_required
def like_answer(id):
    answer = Answer.query.filter_by(id=id).first()
    print answer.likes
    if current_user not in answer.likes:
        try:
            answer.likes.append(current_user._get_current_object())
        except NoneType as detail:
            print 'No Object current user', detail
    return redirect(url_for('main.show_question', id=answer.questionid))

library/templates/_answers.html
<ul class="answers">
    {% for answer in answers %}
    <li class="answer">
        <span class="label label-success label-as-badge">{{ answer.likes|length }}</span>
        <div class="answer-content">
            <div class="answer-date">{{ moment(answer.timestamp).fromNow() }}</div>
            <div class="answer-author">{{ answer.author.username }}</div>
            <div class="answer-body">
                {{ answer.text }}
            </div>
            <div class="answer-footer">
                <div class="answer-likes">
                    {% if current_user not in answer.likes%}
                    <a href="{{ url_for('.like_answer', id=answer.id) }}" method='POST'>
                        <span class="label label-default">Like</span>
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

library/templates/proto.html
{% extends "bootstrap/base.html" %}

{% block title %}Lets make poLibrary!{% endblock %}
{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}
{% block navbar %}
<div class="container" id="topnavbar">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" style="margin-bottom: 10px;"><span
                            class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                            class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a class="navbar-brand" href="/">Library!</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        {% if not current_user.is_authenticated() %}
                        <li>
                            <a href="{{ url_for('auth.login') }}"> <span class="glyphicon glyphicon-log-in"></span> Log
                                In</a>
                        </li>
                        <li>
                            <a href="{{ url_for('auth.register') }}"> <span class="glyphicon"></span>Sign IN</a>
                        </li>
                        {% endif %}
                        {% if current_user.is_authenticated() %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <strong
                                    class="caret"></strong></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ url_for('main.show_questions') }}">All Questions</a>
                                </li>
                                <li class="divider">
                                </li>
                                <li>
                                    <a href="{{ url_for('auth.logout') }}">Log Out</a>
                                </li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    {% if current_user.is_authenticated() %}
                    <form class="navbar-form" role="search" action="{{ url_for('main.search_for_question') }}"
                          method="Post">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for a question..."
                                   name="search_text">
								<span class="input-group-btn">
									<button type="submit" class="btn btn-default">
										<span class="glyphicon glyphicon-search">
											<span class="sr-only">Search for a question...</span>
										</span>
                                    </button>
								</span>
                        </div>
                    </form>
                    {% endif %}
                </div>
            </nav>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<div id="content">
    <div class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    </div>
</div>
{% block page_content%}
<div id="page_content"></div>{% endblock %}
{% block footer %}
<div id="footer">
    <div id="footer" style="margin-top:5px; background-color:#DFEFF0">
        <div class="container">
            <p class="navbar-text pull-left">© 2015 - Site D4F
                <a href="/" target="_blank">Comunity</a>
            </p>
            <a href="/" class="navbar-btn btn-danger btn pull-right">
                <span class="glyphicon glyphicon-star"></span> GO UP</a>
        </div>
    </div>
</div>
{% endblock %}
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

library/templates/question.html
{% extends "proto.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Library - Question{% endblock %}

{% block page_content %}
<li class="question">
    <div class="question-content">
        <div class="question-date">{{ moment(question.timestamp).fromNow() }}</div>
        <div class="question-author">
            <h0>{{ question.author.username }}</h0>
        </div>
        <div class="question-body">
            <h2>{{ question.text }}</h2>
        </div>
        <div class="question-footer">
        </div>
    </div>
</li>
{% if current_user.is_authenticated() %}
<div class="answer-form">
    {{ wtf.quick_form(form) }}
</div>
{% endif %}
{% include '_answers.html' %}
{% endblock %}

library/templates/questions.html
{% extends "proto.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Library! - Questions{% endblock %}
{% block page_content %}
{% for question in questions %}
<li class="question">
    <div class="question-content">
        <div class="question-date">{{ moment(question.timestamp).fromNow() }}</div>
        <div class="question-author"><h1>{{ question.author.username }}</h1></div>
        <div class="question-body">
            <h3>{{ question.text }}</h3>
        </div>
        <div class="question-footer">
            <a href="{{ url_for('.show_question', id=question.id) }}">
                <span class="label label-default">Link</span>
            </a>
        </div>
    </div>
</li>
{% endfor %}
{% if current_user.is_authenticated() %}
<div class="question-form">
    {{ wtf.quick_form(form) }}
</div>
{% endif %}
{% endblock %}%}